### PR TITLE
Expose Body's addShape function via api.addShapes

### PR DESCRIPTION
**Pull request by codynova**
* Expose Body's addShape function via api.addShapes
* Create CompoundBody demo example

We will probably want a `useCompoundBody` hook next, and maybe a `Body.prototype.removeShape` function in `cannon-es`.

We might also want to add a `Body.prototype.recalculateCenterOfMass` function to `cannon-es`, but after trying the formula mentioned here, it didn't seem to be working as I'd expect:
https://github.com/react-spring/use-cannon/issues/29#issuecomment-602400659

### CODE REVIEW

**Comment by drcmda** [comment]
if we have useCompoundBody, do we need add/remove-Shape in the api or should we go for just the hook? just asking for consistency, for instance we have useBox, but there's no imperative way to add a body with a box shape.

**Comment by codynova** [comment]
I was wondering about that as well. I figured this allows for dynamically updating a body's shape from a side effect, or something along those lines. I definitely think a `useCompoundBody` hook will be used more often than `api.setShapes`. I leave it up to you, I feel like you have a significantly better grasp over the dev experience of the API 😃

**Comment by drcmda** [comment]
i think generally i'd shoot for simplicity first even if that cuts into some features. but then again, i don't know what people are doing with physics libs. if it's important that you can set shapes after set up - then by all means ...

**Comment by codynova** [comment]
Makes sense to me. Let's ditch this and stick with the hook only for now.

**Comment by codynova** [comment]
@drcmda Should we just add a `shapes` options to the `useBody` hook, similar to materials - or would you prefer an abstraction like `useCompoundBody`?

**Comment by drcmda** [comment]
i think useompoundBody would be nicer, because we can have the same api:

const [ref, api] = useXyz(() => props)

useBody is a little generic imo

**Pull request closed without merging**
