### PR TITLE
Match API in cannon-es #6

### PR DESCRIPTION
**Pull request by stockHuman**
Pass an object to convexpolyhedron instead of ordered arguments.

### CODE REVIEW

**Comment by codynova** [comment]
Testing this in combination with `cannon-es@0.7.0` yields and error in the ConvexPolyhedron demo:

```
Uncaught TypeError: Cannot read property 'norm2' of undefined
    at ConvexPolyhedron.updateBoundingSphereRadius
    at new ConvexPolyhedron
    at self.onmessage
```

**Comment by stockHuman** [comment]
Right you are, the package.json asks for `cannon-es@^0.6.10`, giving us the old constructor. Were you testing with cannon-es@0.7.0 otherwise installed? Because I just did and it worked well.

**Comment by codynova** [comment]
@stockHuman I believe the changes to ConvexPolyhedron in `cannon-es@0.7.0` breaks the `CubeHeap.js` demo - even after this branch's changes. This is the scenario:

* `use-cannon` on the `master` branch with `cannon-es@0.6.10` - all demos work fine

* `use-cannon` on the `master` branch with `cannon-es@0.7.0` - ConvexPolyhedron demo breaks. This is expected because `use-cannon` is not using the new constructor format.

* `use-cannon` on this branch with `cannon-es@0.6.10` - ConvexPolyhedron demo breaks. This is expected because `cannon-es` is not using the new constructor format.

* `use-cannon` on this branch with `cannon-es@0.7.0` - CubeHeap demo breaks. This is unexpected.

**Comment by drcmda** [comment]
yep, in 0.7.0 there's something that breaks. before and after recent changes.

**Comment by stockHuman** [comment]
Good morning folks, latest changes in cannon-es should have fixed the bug I introduced. Thank you @codynova for the concise testing results. :)

**Comment by codynova** [comment]
I merged this manually alongside the `cannon-es@0.8.0` TypeScript updates due to differences in dependency versions efcb01d

**Comment by stockHuman** [comment]
Thank you :)

**Pull request closed without merging**
