### PR TITLE
Add subscriptions to Worker API

### PR DESCRIPTION
**Pull request by codynova**
Addresses #45.

I think this could be improved by switching to `const subscriptions = new Map()` in the worker, but we should probably talk about the implications first (polyfills for old browsers).

I tested subscribing and unsubscribing to velocity, position, rotation, mass, and allowSleep. I figured that was enough to know they're mostly working 🤷‍♂ 

It also needs to be more strictly typed, but I wanted to get this out there 👋👋👋

### CODE REVIEW

**Comment by codynova** [comment]
Works like this:

```js
useEffect(() => {
  const unsubscribe = api.velocity.subscribe(v => console.log(v))
  return unsubscribe
}, [])
```

i.e.

```js
useEffect(() => api.velocity.subscribe(v => console.log(v)), [])
```

**Comment by codynova** [comment]
Should we make the `self.postMessage({ op: 'observe', ... })` calls async?

**Comment by drcmda** [comment]
the for loop in the worker? looks perfect as it is - or do you mean in another place?

**Comment by codynova** [comment]
Yeah, the for loop in the worker. I was wondering if maybe it would be increase performance to have the resolving function of every loop fire async, similar to how you'd deal with chunking async XMLHTTPRequests - something [like this](https://github.com/intouchgroup/redirect-tester/blob/78d4c19b12bc522ed2607349b6ebd3278accbf97/src/index.ts#L234). No idea if you'd actually get any benefits since it isn't fetching data from a server, but of course the communication between the main thread and worker is already async...

**Comment by drcmda** [comment]
i think it could be linear, but perhaps it's better to re-use the original postmessage:

```jsx

// global re-use
const euler = new Vec3()

// case "step": ...

const subscriptions = []
for (const uuid of Object.keys(subscriptions)) {
  for (const type of subscriptions[uuid]) {
    let value = bodies[uuid][type]
    if (value instanceof Vec3) value = value
    else if (value instanceof Quaternion) value.toEuler((value = euler))
    subscriptions.push([uuid, type, value.toArray()])
  }
}

self.postMessage(
  {
    op: 'frame',
    positions,
    quaternions,
    subscriptions,
    active: world.hasActiveBodies,
  },
  [positions.buffer, quaternions.buffer],
)
```

**Comment by drcmda** [comment]
thinking of it, the same method could be used for hits and raycasts.

**Comment by codynova** [comment]
I went ahead and bundled the worker's returned `observations` into the `frame` postMessage. I think it's a good idea to refactor the other events (collide and rayhit) that way as well - although maybe in another PR

**Comment by drcmda** [comment]
youre so fast :-D  thanks a lot this is great!

**Comment by codynova** [comment]
@drcmda Thanks for the awesome suggestions! 🎺

**Pull request merged**
